### ISSUE TITLE
Building for 'iOS-simulator', but linking in object file ... built for 'iOS'

### ISSUE THREAD

**Issue by teklot** [jcsawyer/Jc.AdMob.Avalonia#1] opened 2024-12-04 21:35 UTC
Thanks for the awesome package. It works great with android project, but I get the following error when the package is added to the iOS project and built:
```
clang++ exited with code 1:
ld: building for 'iOS-simulator', but linking in object file ... built for 'iOS'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
Would you please help with this? Thanks!

**Comment by jcsawyer** [comment] 2024-12-05 12:32
Just to help narrow down the issue, are you on a intel or apple silicon mac?

**Comment by teklot** [comment] 2024-12-05 13:18
I am using a Mac mini desktop computer with Apple M4 chip. In more details, I should say I am on a Windows machine using Visual Studio paired with the aforementioned Mac mini to build and run my app. The app is built and run without the Jc.AdMob.Avalonia.iOS package.

Yes, I have got the ```<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>``` in my ```csproj```.

Thanks for looking into this issue.

**Comment by jcsawyer** [comment] 2024-12-05 14:50
Thanks for your response.
I'm currently unable to reproduce. Are you able to reproduce with the sample project?

**Comment by teklot** [comment] 2024-12-05 15:12
Yes, I am able to reproduce the error with the sample project ```Jc.AdMob.Avalonia.Sample.iOS```.

```
clang++ exited with code 1:
ld: building for 'iOS-simulator', but linking in object file (/Users/dev/Library/Caches/Xamarin/mtbs/builds/Jc.AdMob.Avalonia.Sample.iOS/1bafa2b9ca26383ffc093fb136de57fd6c9dc3ade4b12461d703532718a75bc1/C:/Users/dev/AppData/Local/XamarinBuildDownloadCache/GUsrMess-1.1.0/Frameworks/Release/UserMessagingPlatform.framework/UserMessagingPlatform[arm64][2](UMPView.o)) built for 'iOS'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jcsawyer** [comment] 2024-12-05 19:25
I suspect it may have something to do with the iOS bindings project. 
Are you able to confirm whether `v1.2.1` builds on your end?

**Comment by teklot** [comment] 2024-12-05 20:54
The package ```v1.2.1``` does not build, same error plus a couple of others:
```
The "XamarinDownloadArchives" task could not be initialized with its input parameters. 

The "AndroidFixManifests" parameter is not supported by the "XamarinDownloadArchives" task loaded from assembly: Xamarin.Build.Download, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from the path: C:\Users\dev\.nuget\packages\xamarin.build.download\0.11.4\buildTransitive\Xamarin.Build.Download.dll. Verify that the parameter exists on the task, the <UsingTask> points to the correct assembly, and it is a settable public instance property.
```

**Comment by jcsawyer** [comment] 2024-12-05 20:55
Interesting. Leave it with me, I'll see if I can reproduce when I can access my Windows machine.

**Comment by jcsawyer** [comment] 2024-12-07 14:06
So I can reproduce! It seems to be an issue with mac agents in Visual Studio specifically. Not entirely sure what's going on there, will do my best to investigate. It also seems to impact Rider's mac agent pieces so potentially something with how they build on remote agents compared to being built directly on a mac. 

There is at least one possible workaround, if you don't require rewarded ads, dropping back down to `v1.2.1` and adding the latest package `Xamarin.Build.Download` _should_ resolve the issues you ran into previously.

The other workaround of course would be to target for a real device, but I appreciate that's probably not convenient or feasible.

**Comment by jcsawyer** [comment] 2024-12-07 15:17
Further investigation, it looks like the issue is with UMP. 
I may have to add bindings to the project similarly to the mobile ads sdk. This may take some time though. So rolling back even further prior to UMP consent was added which is obviously not ideal.

**Comment by teklot** [comment] 2024-12-07 16:05
> Further investigation, it looks like the issue is with UMP. I may have to add bindings to the project similarly to the mobile ads sdk. This may take some time though. So rolling back even further prior to UMP consent was added which is obviously not ideal.

I appreciate the time and efforts you've put in to develop the package and investigate the issue. Thanks!

**Comment by jcsawyer** [comment] 2024-12-07 17:54
@teklot Can you try using the latest preview `1.4.1-preview100` (might take a short while to appear) and see if it makes any difference?

**Comment by teklot** [comment] 2024-12-08 01:13
@jcsawyer, with the ```1.4.1-preview100``` I get one different error:

```
clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth", referenced from:
      <initial-undefines>
  "_GADGoogleAdNetworkClassName", referenced from:
      <initial-undefines>
  "_GADMaxAdContentRatingGeneral", referenced from:
      <initial-undefines>
  "_GADMaxAdContentRatingMatureAudience", referenced from:
      <initial-undefines>
  "_GADMaxAdContentRatingParentalGuidance", referenced from:
      <initial-undefines>
  "_GADMaxAdContentRatingTeen", referenced from:
      <initial-undefines>
  "_GADNativeAdChoicesViewAsset", referenced from:
      <initial-undefines>
  "_GADNativeAdvertiserAsset", referenced from:
      <initial-undefines>
  "_GADNativeBodyAsset", referenced from:
      <initial-undefines>
  "_GADNativeCallToActionAsset", referenced from:
      <initial-undefines>
  "_GADNativeHeadlineAsset", referenced from:
      <initial-undefines>
  "_GADNativeIconAsset", referenced from:
      <initial-undefines>
```

**Comment by jcsawyer** [comment] 2024-12-08 22:25
Awesome. I think that's one issue down as these are coming from the other binding. But I'm away from keyboard for a few days. Will take a look at this when I'm back.
Many of these bindings look unused, bar one, so as a workaround I'm thinking disabling them.

**Comment by jcsawyer** [comment] 2024-12-11 12:22
Did a bit of an investigation last night and it seems removing unused bindings may be a dead end - just causes a lot more errors. I am actively working on it, but it's back to the drawing board for now - possibly even need to switch over to net8 ios bindings to find a proper solution but won't have significant time until end of week.

This is a very weird one and rather new territory for me so I hope you're able to work around it for now.
Thanks for your patience.

**Comment by jcsawyer** [comment] 2024-12-12 02:07
Okay, don't want to get hopes up too early. It's rather late and I've stayed up way too long but I think I'm mostly there. 
Have some further testing to do tomorrow but it looks like I've got it running in Windows paired to my Mac. Should be all ready by the weekend.
![image](https://github.com/user-attachments/assets/b295a15e-d12a-4cbc-b26b-491df400c2bf)

**Comment by teklot** [comment] 2024-12-12 02:50
@jcsawyer, Thank you for the efforts and your time. Eager to hear from you soon.

**Comment by jcsawyer** [comment] 2024-12-12 19:46
@teklot Please give `1.4.1-preview200` a try and let me know how you get on.

**Comment by teklot** [comment] 2024-12-12 22:12
Used the ```1.4.1-preview200``` after ```nuget locals all -clear```. The good news is it successfully builds and brings up the simulator but gives me the following run-time error:

```
ObjCRuntime.ObjCException
  Message=Objective-C exception thrown.  Name: GADInvalidInitializationException Reason: The Google Mobile Ads SDK was initialized without AppMeasurement. Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-update-plist to include the AppMeasurement framework and set the -ObjC linker flag. Google Ad Manager publishers, follow instructions here: https://googlemobileadssdk.page.link/ad-manager-ios-update-plist
Native stack trace:
	0   CoreFoundation                      0x00000001804b757c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018008eda8 objc_exception_throw + 72
	2   CoreFoundation                      0x00000001804b7110 -[NSException init] + 0
	3   Jc.AdMob.Avalonia.Sample.iOS        0x0000000104cacda4 GADApplicationVerifyPublisherInitializedAnalyticsCorrectly + 348
	4   Jc.AdMob.Avalonia.Sample.iOS        0x0000000104c5c71c GADEnvironmentIsSupported + 748
	5   libdispatch.dylib                   0x00000001801774ec _dispatch_call_block_and_release + 24
	6   libdispatch.dylib                   0x0000000180178de0 _dispatch_client_callout + 16
	7   libdispatch.dylib                   0x000000018017c338 _dispatch_queue_override_invoke + 1380
	8   libdispatch.dylib                   0x000000018018b518 _dispatch_root_queue_drain + 364
	9   libdispatch.dylib                   0x000000018018bf60 _dispatch_worker_thread2 + 232
	10  libsystem_pthread.dylib             0x0000000118bafb38 _pthread_wqthread + 224
	11  libsystem_pthread.dylib             0x0000000118bae934 start_wqthread + 8

  Source=Microsoft.iOS
  StackTrace:
   at ObjCRuntime.Runtime.ThrowNSException(IntPtr ns_exception) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 564
   at ObjCRuntime.Runtime.throw_ns_exception(IntPtr exc) in /Users/builder/azdo/_work/1/s/xamarin-macios/runtime/Delegates.generated.cs:line 279
```

I tried both the ```Jc.AdMob.Avalonia.Sample.iOS``` and my project and they both throw the same error above. I double-cheked  the plist and it seems correct but not sure how to set the ```-ObjC Linker Flag``` when the project is paired with my Mac through Visual Studio on Windows. Is this something that needs to be done on XCode running on Mac?

Thanks!

**Comment by jcsawyer** [comment] 2024-12-13 01:35
Does it work if you add:
```
<key>GADIsAdManagerApp</key>
<true/>
```
to the `info.plist`?

(currently working with some old bindings I plan to update now I've shifted them over)

**Comment by teklot** [comment] 2024-12-13 01:57
Yes, added the ```<key>GADIsAdManagerApp</key> <true/>``` to the ```info.plist``` and it worked!

**Comment by jcsawyer** [comment] 2024-12-13 02:26
Release `v1.4.1` with release binding packages should now be available on NuGet.
Closing this one out.

**Closed by jcsawyer** 2024-12-13 02:26 UTC
Labels: bug

**Comment by teklot** [comment] 2024-12-13 13:13
> Release `v1.4.1` with release binding packages should now be available on NuGet. Closing this one out.

Thank you so much!
